version: '3.8'

services:
  flask-app:
    network_mode: bridge
    build:
      context: https://github.com/fruitcake514/qrcode-reader.git
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      FLASK_ENV: development
    restart: unless-stopped
