version: '3.8'

services:
  flask-app:
    network_mode: bridge
    build:
      context: https://github.com/fruitcake514/qrcode-reader.git
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    environment:
      FLASK_ENV: development
    restart: unless-stopped
